apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:3cmWPwhI8i7+MnKOYdv1ib/78+wT2nCMCDbgICzyQAHAVoGCvseKIw==,iv:Ps+nyhm4YMRs/kR2YoCLxzcE8Xsv9cgeqm9vY+rF2sU=,tag:53KjHrpzLUIl3cBVKeB99w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gz9latge3y94hecqmjy3z9swp08c59pxy683uttfaqss0famtfzsr46nq9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtYXdQQWNnb0FneDFiV3h0
            VXgzb1B1V0xQYXNTczhYYXRMcXArKzJ5L1FBCmdQdUZXejJWT3NPcTlqSmhEcldC
            WVRmY2RaV2tzb3pKdWJyZUc1ajlGNUEKLS0tIGFFUk9zZ0RqcG1BQmszWGRNak9w
            Y3hweitnY0l6ZG9CYWNnU1B4Q1IzRm8KQ3TxfxTXiy5A4U42GvfyrGC9zSCQuteO
            S4xgRkz6Y4q+hymiMgTQw89uN0JOdyCEEBve30Qrb9spqKCndrFJiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-25T07:16:20Z"
    mac: ENC[AES256_GCM,data:mwnCKvvqC+KN7ABQYMa4q/iZWb4Qypt59Gy/C24S7bcaUPw43xeAQj+4XVGpywj7zNih2LSDY4IiTRpDFPDy+rfv6guLiaD7emcvN9x93gkULcO3if1lqerFRWYE2JbQadouaHRijXlAmS7MCjGqY7mMoOIEepuGDQbLEScAejk=,iv:voXrvMxEm3Km3199bXqr//acMIvyUJFpW0uSEBVp//k=,tag:zJ0BK4pnqyUhnXmH/R4a6g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
