apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:DWZnwSUuCRsXjKT/REoblmTZMO+cmqs4+Gq4Vnsp0gfRgpKKc7mHeA==,iv:on+dCkXJ/Xtlg+hgL7Oj8zQFQrW4x8YmOV6tbTJuRsw=,tag:z4rRkIGBjjItOBAqHu+oyg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gz9latge3y94hecqmjy3z9swp08c59pxy683uttfaqss0famtfzsr46nq9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0QWI2ZHpHYk9sQ1E1c1Ju
            L0tjOXpTOGNzQnhtTUNsZTM2ZVFqOHlEekVjCjhsY2NjcEx5Y2N1K1JCRkFwYTk4
            YkVZZXFzOEpTUWY5Znk5SUlYTGc5KzgKLS0tIDRYQXUrZGVXa0ZBRUVLWGJyMXJ2
            a2dVbTdvUnRCNHNUQUE1OURmOHBhdU0KZgtxAcNB6SoR8Omd6li3T4oXpxuxkU+l
            EzzYXLYA/qqpI1bM4FE4MHgnVMwl6iDnLylnKkBh/Lj7EI2LmGvb4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-25T07:20:00Z"
    mac: ENC[AES256_GCM,data:BFISiGt17QVv7bzyKwyj/8VHK4BgkScvqFIaFp3UIhGZVMcrqvpWBgu0jywsS5f3FgN/Q4xxcLZVeFm3h37vrRFxAOlQVV8kLi4zzFtU9Ftmol9b5cJrV/Frzm91S8Tw22DbqHxjAE79qnN98LaVw5W+Tp4ELoKn47Mhohdy98s=,iv:kXeOrbbFzssaAhaBQCwLPEBfRLcsOpGo6ww8bItcj2E=,tag:kT9zvGtmFkU0NmmXqaShmA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
