apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:bRCP/H0DNakUEQIU2pyIkzONjH2fki07,iv:ah6nPkPRyrq9mzOGzbftJLqTeVPYlu4pyxSSxcjTUT0=,tag:pNmgWcVufk1dqw/XNKCGCQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gz9latge3y94hecqmjy3z9swp08c59pxy683uttfaqss0famtfzsr46nq9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxVjZsa0Fqc3ZYM0JmUmFB
            T2dDV0lBRVVRSXVHLzNJSk9WTmhXYU02NUJJCnhCaGwzeVkzaWFvaGYyeldTT2hj
            UXd6anpwWmZJQXVQbFlwYm1LdnU3UncKLS0tIENRaWJXWjUzblg4dmxWT0RpSUJH
            QmdDUG41S3pvbmc3SlZhMHZTQ3RobzQKIJ1yhz5VAuXVGBxhv5OrEr2pQgLnv7rx
            5bLYRuIn431PuzCRsPDKUJCkVX/N6eRK1PLqnvpf0Liucavg1Xj+Xg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-25T16:28:05Z"
    mac: ENC[AES256_GCM,data:yFM9IKcfq2cCiiKT0gZOcDqZD+Lb5lemEx49aUAJWVvudWT25lYB3AU1MJ5CnOsy6o9TFl7rEPJDqQ+mTsxhYAysJXVvRCLbklCOiS/bV82CEyjMx2D0gISv+Zor4FAeCp+X/1+5CPm5S5HDWS8f3B9gy0ucp/F8JrxRoxl7NNc=,iv:HEHdFe8mq5IhpLjxZn+Kng8jPf19XiCapQwt6pyp75E=,tag:ABGoUpKGx6AtYHUBF0A6Zg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
